#!/bin/bash

# Configure ssmtp
conf-ssmtp

. /usr/share/xymon/init-common.sh

test -f /etc/xymon/hosts.cfg || tar -C /etc/xymon -xzf /root/xymon-config.tgz
test -d /var/lib/xymon/rrd || tar -C /var/lib/xymon -xzf /root/xymon-data.tgz

rm -f /var/lib/xymon/tmp/*[0-9]*

egrep -q "^CLIENTHOSTNAME=\"${HOSTNAME}\"" /etc/default/xymon-client
if [ $? -ne 0 ]
then
	sed -i "s/^CLIENTHOSTNAME.*/CLIENTHOSTNAME=\"${HOSTNAME}\"/" /etc/default/xymon-client
	sed -i "s@^127.0.0.1.*@127.0.0.1\t${HOSTNAME}\t# bbd http://${HOSTNAME}/@" /etc/xymon/hosts.cfg
fi

# Include xymon-client defaults if available
if [ -f /etc/default/xymon-client ] ; then
	. /etc/default/xymon-client
fi

create_includefiles

exec start-stop-daemon --exec /usr/lib/xymon/server/bin/xymonlaunch --chuid xymon --umask 022 --start \
	-- \
	--config=/etc/xymon/tasks.cfg \
	--env=/etc/xymon/xymonserver.cfg \
	--log=/var/log/xymon/xymonlaunch.log \
	--no-daemon
